// Session recap — the rules behind the sidebar's "where was I?" card.
//
// The fixtures below are REAL wrapper shapes taken from live transcripts, not
// invented ones. That matters most for the slash-command case: running `/compact`
// writes a user turn, so the newest user turn in a just-compacted session is a
// command echo rather than anything the human typed. A recap that reports "your
// last prompt was: compact" is worse than no recap at all, because it is
// confidently wrong.
const { test, expect } = require('@playwright/test');
const {
  buildRecap,
  classifyUserTurn,
  isHumanPrompt,
  findHumanPromptIndex,
  findHumanPromptIndexes,
  condense,
  toolTally,
  summariseTasks,
  USER_KINDS,
  MAX_PROMPTS,
  PROMPT_CHARS,
  PROMPT_TRAIL_CHARS,
} = require('../lib/recap');

const user = (text, ts = null) => ({ role: 'user', text, toolUses: [], ts });
const asst = (text, toolUses = [], ts = null) => ({ role: 'assistant', text, toolUses, ts });
const tool = (name) => ({ name, id: 't' + name, inputPreview: '{}', input: {} });

// --- real injection wrappers -------------------------------------------------
// A slash command surfaces as two DISJOINT real shapes — never fused into one
// turn the way this file used to fuse them: a trio led by <command-name> (what
// a bare command like `/compact` itself writes) and a <local-command-caveat>-led
// turn carrying no trio at all (what the command's own stdout produces).
// The counts behind that live with the rule they justify, in lib/user-turn.js —
// restating them here is how one fact becomes two that drift. Mirrors the same
// split in tests/user-turn.spec.js's TRIO_NAME_FIRST / CAVEAT_LEAD.
const SLASH_COMPACT = [
  '<command-name>/compact</command-name>',
  '<command-message>compact</command-message>',
  '<command-args></command-args>',
].join('\n');
const CAVEAT_LEAD =
  '<local-command-caveat>Caveat: The messages below were generated by the user while running local commands. DO NOT respond to these messages.</local-command-caveat>';
const TASK_NOTIFICATION =
  '<task-notification><summary>Agent "search" finished</summary><result>Found it at server.js:42</result></task-notification>';
const TEAMMATE =
  'Another Claude session sent a message: <teammate-message teammate_id="J4b2">please rebase</teammate-message>';
const REMINDER_ONLY = '<system-reminder>Background context you should not act on.</system-reminder>';
const PROMPT_WITH_REMINDER =
  'fix the login bug\n<system-reminder>\n# claudeMd\nlots of injected instructions\n</system-reminder>';

test.describe('classifyUserTurn', () => {
  test('a plain sentence is a human prompt, unchanged', () => {
    const c = classifyUserTurn('add a recap icon to the sidebar');
    expect(c.kind).toBe(USER_KINDS.HUMAN);
    expect(c.body).toBe('add a recap icon to the sidebar');
  });

  test('a slash command is NOT a prompt', () => {
    // The regression this module exists for.
    const c = classifyUserTurn(SLASH_COMPACT);
    expect(c.kind).toBe(USER_KINDS.COMMAND);
    expect(c.from).toBe('/compact');
  });

  test('the caveat prose alone is still a command', () => {
    // When the command produced stdout the caveat arrives without its tag.
    const c = classifyUserTurn(
      'Caveat: The messages below were generated by the user while running local commands. DO NOT respond.');
    expect(c.kind).toBe(USER_KINDS.COMMAND);
  });

  test('a task-notification is system, and keeps only the result', () => {
    const c = classifyUserTurn(TASK_NOTIFICATION);
    expect(c.kind).toBe(USER_KINDS.SYSTEM);
    expect(c.from).toBe('search');
    expect(c.body).toBe('Found it at server.js:42');
  });

  test('a teammate message carries the sender id', () => {
    const c = classifyUserTurn(TEAMMATE);
    expect(c.kind).toBe(USER_KINDS.TEAMMATE);
    expect(c.from).toBe('J4b2');
    expect(c.body).toBe('please rebase');
  });

  test('stop-hook feedback is system', () => {
    expect(classifyUserTurn('Stop hook feedback: run the tests').kind).toBe(USER_KINDS.SYSTEM);
  });

  test('a post-compaction summary is system', () => {
    expect(classifyUserTurn('This session is being continued from a previous conversation…').kind)
      .toBe(USER_KINDS.SYSTEM);
  });

  test('a system-reminder is STRIPPED from a real prompt', () => {
    // A genuine prompt arrives with injected context stapled on. Showing it would
    // bury the user's own sentence under a screenful of instructions.
    const c = classifyUserTurn(PROMPT_WITH_REMINDER);
    expect(c.kind).toBe(USER_KINDS.HUMAN);
    expect(c.body).toBe('fix the login bug');
    expect(c.body).not.toContain('claudeMd');
  });

  test('a turn that is ONLY a system-reminder is not a prompt', () => {
    const c = classifyUserTurn(REMINDER_ONLY);
    expect(c.kind).toBe(USER_KINDS.SYSTEM);
    expect(c.body).toBe('');
  });

  test('non-string input never throws', () => {
    expect(classifyUserTurn(undefined).kind).toBe(USER_KINDS.SYSTEM);
  });
});

test.describe('condense', () => {
  test('collapses whitespace and leaves short text intact', () => {
    expect(condense('a\n\n  b   c', 100)).toBe('a b c');
  });

  test('cuts on a word boundary and marks the cut', () => {
    const src = 'alpha bravo charlie delta echo foxtrot';
    const out = condense(src, 20);
    expect(out.endsWith('…')).toBe(true);
    expect(out.length).toBeLessThanOrEqual(21);
    // Every surviving word must be WHOLE — i.e. the kept text is a word-aligned
    // prefix of the source. (Asserting "no letter before the ellipsis" would be
    // wrong: a correctly cut word ends in a letter too.)
    const kept = out.slice(0, -1);
    expect(src.startsWith(kept)).toBe(true);
    expect(src[kept.length]).toBe(' ');
  });

  test('drops fenced code blocks', () => {
    const out = condense('before\n```js\nconst x = 1;\n```\nafter', 200);
    expect(out).toContain('before');
    expect(out).toContain('after');
    expect(out).not.toContain('const x');
  });
});

test.describe('toolTally', () => {
  test('tallies rather than lists', () => {
    const turns = [asst('', [tool('Edit'), tool('Edit'), tool('Bash')])];
    expect(toolTally(turns)).toEqual(['Edit ×2', 'Bash']);
  });

  test('is capped so it stays a glance', () => {
    const turns = [asst('', ['A', 'B', 'C', 'D', 'E', 'F'].map(tool))];
    expect(toolTally(turns, 3)).toHaveLength(3);
  });
});

test.describe('summariseTasks', () => {
  const list = [
    { id: 1, subject: 'Vendor xterm', status: 'completed' },
    { id: 2, subject: 'Wire the endpoint', status: 'in_progress' },
    { id: 3, subject: 'Add the icon', status: 'pending' },
  ];

  test('counts done and names the in-progress task', () => {
    expect(summariseTasks(list)).toEqual({
      done: 1, total: 3, current: 'Wire the endpoint', currentIsActive: true,
    });
  });

  test('falls back to the first open task when nothing is in progress', () => {
    // A list with no in_progress still has an obvious "next"; leaving the most
    // useful line on the card blank would waste it.
    const s = summariseTasks([
      { id: 1, subject: 'done thing', status: 'completed' },
      { id: 2, subject: 'next thing', status: 'pending' },
    ]);
    expect(s.current).toBe('next thing');
    expect(s.currentIsActive).toBe(false);
  });

  test('an update whose create was never seen still shows, by id', () => {
    // Mirrors lib/task-list.js: dropping it would hide in-progress work, which is
    // the one thing the panel exists to surface.
    expect(summariseTasks([{ id: 9, subject: '', status: 'in_progress' }]).current)
      .toBe('Task #9');
  });

  test('absent or empty lists yield null so the row is omitted', () => {
    expect(summariseTasks(null)).toBeNull();
    expect(summariseTasks([])).toBeNull();
  });
});

test.describe('buildRecap', () => {
  test('finds the last HUMAN prompt, skipping newer injected turns', () => {
    // The realistic ordering: you asked something, work happened, then a
    // task-notification and a slash command's caveat landed after it.
    const r = buildRecap([
      user('why is the terminal blank?', '2026-08-02T10:00:00Z'),
      asst('Looking now.', [tool('Read')]),
      user(TASK_NOTIFICATION),
      user(CAVEAT_LEAD),
    ]);
    expect(r.prompt.text).toBe('why is the terminal blank?');
    expect(r.prompt.at).toBe('2026-08-02T10:00:00Z');
  });

  test('reports the agent reply that came after the prompt', () => {
    const r = buildRecap([
      asst('an older answer nobody asked about'),
      user('what broke?'),
      asst('The buffer aliased its lines.', [], '2026-08-02T11:00:00Z'),
    ]);
    expect(r.reply.text).toBe('The buffer aliased its lines.');
    expect(r.reply.at).toBe('2026-08-02T11:00:00Z');
  });

  test('prefers an author-marked TL;DR over the opening prose', () => {
    // Reuses lib/speech.js's extractSummary — the TL;DR section is written to be
    // exactly this: a standalone recap of a long answer.
    const r = buildRecap([
      user('explain the fix'),
      asst('Long preamble with lots of detail that nobody wants in a card.\n\n## TL;DR\nThe scroll aliased lines.'),
    ]);
    expect(r.reply.isSummary).toBe(true);
    expect(r.reply.text).toBe('The scroll aliased lines.');
  });

  test('skips tool-only turns when choosing the reply', () => {
    const r = buildRecap([
      user('go'),
      asst('Starting the build.'),
      asst('', [tool('Bash')]),
    ]);
    expect(r.reply.text).toBe('Starting the build.');
  });

  test('summarises the work done SINCE the prompt', () => {
    const r = buildRecap([
      asst('', [tool('Grep')]), // before the prompt — must not be counted
      user('fix it'),
      asst('', [tool('Edit'), tool('Edit')]),
      asst('', [tool('Bash')]),
    ]);
    expect(r.since.turns).toBe(2);
    expect(r.since.tools).toEqual(['Edit ×2', 'Bash']);
  });

  test('a session with no human turn yields a null prompt, not an error', () => {
    // An autoCommand-started agent may genuinely have no typed prompt in the
    // window. The reply still falls back to the newest prose so the card is useful.
    const r = buildRecap([asst('Booting up.')]);
    expect(r.prompt).toBeNull();
    expect(r.reply.text).toBe('Booting up.');
  });

  test('empty input is safe', () => {
    const r = buildRecap([]);
    expect(r.prompt).toBeNull();
    expect(r.reply).toBeNull();
    expect(r.since).toEqual({ turns: 0, tools: [] });
  });

  test('a long prompt is truncated and says so', () => {
    const r = buildRecap([user('word '.repeat(300))]);
    expect(r.prompt.truncated).toBe(true);
    expect(r.prompt.text.length).toBeLessThan(420);
  });
});

// --- #163: a skill body must never be reported as "your last prompt" ----------
// The failure this module exists to prevent, arriving through the one shape it
// could not see. A skill is expanded into a `role:user` turn carrying the whole
// SKILL.md and NO wrapper, so every content signature misses it and the recap
// card confidently announced 142 KB of skill instructions as the user's sentence.
// The transcript record says otherwise structurally (`isMeta: true`), and
// lib/transcript.js now publishes that verdict on the turn as `userKind`.
const SKILL_BODY =
  'Base directory for this skill: /skills/example-skill\n\n# Example skill\n\nDo the thing.';
// The measured opening that a `Base directory` sniff would miss — kept here too
// so a regression into content-sniffing fails the recap as well as the rule.
const SKILL_BODY_HEADING = '# Frontend Design\n\nApproach this as the design lead.';
const meta = (text, ts = null) =>
  ({ role: 'user', text, toolUses: [], ts, userKind: USER_KINDS.META });

test.describe('#163 — skill injections and the last prompt', () => {
  test('the real typed prompt survives underneath a pile of skill bodies', () => {
    const r = buildRecap([
      user('rewrite the deploy script', '2026-08-26T09:00:00Z'),
      asst('on it'),
      meta(SKILL_BODY, '2026-08-26T09:01:00Z'),
      meta(SKILL_BODY_HEADING, '2026-08-26T09:02:00Z'),
    ]);
    expect(r.prompt.text).toBe('rewrite the deploy script');
    expect(r.prompt.at).toBe('2026-08-26T09:00:00Z');
  });

  test('with nothing but skill bodies the recap reports NO prompt', () => {
    // Absent beats wrong. A null prompt is a normal, honest answer here.
    const r = buildRecap([meta(SKILL_BODY), asst('done'), meta(SKILL_BODY_HEADING)]);
    expect(r.prompt).toBeNull();
  });

  test('the scan stop-condition agrees with the build — no false stop', () => {
    // findHumanPromptIndexes is what the /recap route pages against (#246 — it
    // counts, because the stop condition is now K prompts); if it stops on a turn
    // buildRecap then rejects, the route pages forever and reports nothing.
    const turns = [user('the real one'), meta(SKILL_BODY), meta(SKILL_BODY_HEADING)];
    expect(findHumanPromptIndexes(turns)).toEqual([0]);
    expect(findHumanPromptIndex(turns)).toBe(0);
    expect(isHumanPrompt(turns[1])).toBe(false);
  });

  test('a turn with no userKind falls back to the text rule (Codex, old pages)', () => {
    // Only the Claude adapter reads isMeta; a Codex rollout turn carries no field
    // at all and must behave exactly as it did before.
    expect(isHumanPrompt(user('fix the login bug'))).toBe(true);
    expect(isHumanPrompt(user(SLASH_COMPACT))).toBe(false);
    expect(isHumanPrompt({ ...user('fix it'), userKind: 'not-a-kind' })).toBe(true);
  });

  test('an ordinary prompt is still reported — the guard', () => {
    const r = buildRecap([user('add a recap icon to the sidebar', '2026-08-26T10:00:00Z')]);
    expect(r.prompt.text).toBe('add a recap icon to the sidebar');
  });
});

// --- #246: one prompt is not enough state to re-orient on --------------------
// Reported from the phone as "that was not my last prompt". The SELECTION was
// correct — a 13h-old prompt with 598 turns and ~40 injected user turns behind
// it, every one of them classified right — and the card was still useless,
// because a single entry cannot show that half a day passed. The fix is a TRAIL:
// the same newest prompt, plus the ones before it, each with its own stamp.
//
// The padding temptation is the thing to guard against. Filling the list out of
// task-notifications or slash-command echoes would make it LONGER and strictly
// less true, which is the failure #163/#192 already paid for once.
test.describe('#246 — the recent-prompt trail', () => {
  const THREE = [
    user('the oldest thing I typed', '2026-09-07T10:00:00Z'),
    asst('working on it', [tool('Read')]),
    user('the middle thing I typed', '2026-09-07T15:21:14Z'),
    asst('still going', [tool('Bash')]),
    user('the newest thing I typed', '2026-09-08T04:41:06Z'),
    asst('done', [tool('Edit')]),
  ];

  test('lists the recent prompts newest FIRST, each with its own stamp', () => {
    const r = buildRecap(THREE);
    expect(r.prompts.map((p) => p.text)).toEqual([
      'the newest thing I typed',
      'the middle thing I typed',
      'the oldest thing I typed',
    ]);
    // The stamps are what make a 13h gap legible; a shared one would not.
    expect(r.prompts.map((p) => p.at)).toEqual([
      '2026-09-08T04:41:06Z', '2026-09-07T15:21:14Z', '2026-09-07T10:00:00Z',
    ]);
  });

  test('`prompt` IS `prompts[0]` — the wire change is additive', () => {
    // The whole reason a client that has not been rebuilt renders exactly as it
    // does today. Identity, not equality: two derivations of "the newest prompt"
    // is the drift this repo keeps paying for.
    const r = buildRecap(THREE);
    expect(r.prompt).toBe(r.prompts[0]);
    expect(r.prompt.text).toBe('the newest thing I typed');
  });

  test('the trail is capped, and the cap is the module\'s own number', () => {
    const many = [];
    for (let i = 0; i < 10; i++) many.push(user(`prompt ${i}`, `2026-09-0${i % 9}T00:00:00Z`));
    expect(buildRecap(many).prompts).toHaveLength(MAX_PROMPTS);
  });

  test('only HUMAN turns qualify — the list is never PADDED to fill it', () => {
    // Fewer, true entries beat three entries of which two are plumbing.
    const r = buildRecap([
      user('the one real prompt', '2026-09-08T01:00:00Z'),
      user(TASK_NOTIFICATION, '2026-09-08T02:00:00Z'),
      user(SLASH_COMPACT, '2026-09-08T03:00:00Z'),
      user(TEAMMATE, '2026-09-08T04:00:00Z'),
      meta(SKILL_BODY, '2026-09-08T05:00:00Z'),
    ]);
    expect(r.prompts).toHaveLength(1);
    expect(r.prompts[0].text).toBe('the one real prompt');
  });

  test('a session with ONE prompt in the window is unchanged', () => {
    // The common case must not regress: same single entry, same fields.
    const r = buildRecap([user('only one', '2026-09-08T04:00:00Z'), asst('ok')]);
    expect(r.prompt).toEqual({ text: 'only one', at: '2026-09-08T04:00:00Z', truncated: false });
    expect(r.prompts).toEqual([r.prompt]);
  });

  test('no prompt at all yields an EMPTY list, never a null one', () => {
    // The client iterates it; a null would be a null-check in two clients for a
    // case the server can answer once.
    const r = buildRecap([asst('Booting up.')]);
    expect(r.prompt).toBeNull();
    expect(r.prompts).toEqual([]);
  });

  test('the trail gets its own SMALLER budget — K prompts are not K × the bytes', () => {
    const long = 'word '.repeat(300);
    const r = buildRecap([user(long, 'a'), user(long, 'b')]);
    expect(r.prompts[0].text.length).toBeGreaterThan(PROMPT_TRAIL_CHARS);
    expect(r.prompts[0].text.length).toBeLessThanOrEqual(PROMPT_CHARS + 1);
    expect(r.prompts[1].text.length).toBeLessThanOrEqual(PROMPT_TRAIL_CHARS + 1);
    expect(r.prompts[1].truncated).toBe(true);
  });

  test('`since` still counts from the NEWEST prompt — the guard', () => {
    // The trail must not move where "what has it done since" starts measuring.
    const r = buildRecap(THREE);
    expect(r.since.turns).toBe(1);
    expect(r.since.tools).toEqual(['Edit']);
  });

  test('findHumanPromptIndexes returns newest-first indexes, capped', () => {
    // The route pages against this, so its order and cap are contract, not detail.
    expect(findHumanPromptIndexes(THREE)).toEqual([4, 2, 0]);
    expect(findHumanPromptIndexes(THREE, 2)).toEqual([4, 2]);
    expect(findHumanPromptIndexes([asst('nothing typed')])).toEqual([]);
    // And the single-index form still answers exactly what it used to.
    expect(findHumanPromptIndex(THREE)).toBe(4);
    expect(findHumanPromptIndex([asst('nothing typed')])).toBe(-1);
  });
});
