// @ts-check
// lib/user-turn.js — what a `role:user` turn actually IS, and what the human
// typed to produce it.
//
// The fixtures below are REAL wrapper shapes lifted from live transcripts, with
// the prose replaced. That matters more here than anywhere else in the suite,
// because #149 was caused by building on an INVENTED shape: a slash command was
// assumed to arrive as a lone `<command-name>/compact</command-name>`, and it
// never does — it is a tag TRIO, in either order, and the order that carries the
// user's arguments is the one that leads with `<command-message>`.
//
// `typedTextOf` is what the chat lens's optimistic "Queued" echo compares itself
// against. Its contract is narrow and absolute: the exact characters the user
// typed into the compose bar, or '' for every turn they typed nothing at all.
const { test, expect } = require('@playwright/test');
const { classifyUserTurn, typedTextOf, USER_KINDS } = require('../lib/user-turn');
const recap = require('../lib/recap');

// --- real wrapper shapes -----------------------------------------------------
// Name-first: what the harness itself writes for a bare `/compact`, `/clear`.
const TRIO_NAME_FIRST = [
  '<local-command-caveat>Caveat: The messages below were generated by the user while running local commands. DO NOT respond to these messages.</local-command-caveat>',
  '<command-name>/clear</command-name>',
  '<command-message>clear</command-message>',
  '<command-args></command-args>',
].join('\n');
// Message-first: the shape a user-typed `/name <text>` actually lands in. This
// is the one that matters for #149 — it is the shape that gets QUEUED.
const TRIO_MESSAGE_FIRST = [
  '<command-message>issue</command-message>',
  '<command-name>/issue</command-name>',
  '<command-args>the queued badge never clears once the prompt is consumed</command-args>',
].join('\n');
const CAVEAT_ONLY =
  'Caveat: The messages below were generated by the user while running local commands. DO NOT respond to these messages.';
const REMINDER = '<system-reminder>\n# claudeMd\nlots of injected instructions\n</system-reminder>';
const TEAMMATE =
  'Another Claude session sent a message: <teammate-message teammate_id="J4b2">please rebase</teammate-message>';
const TASK_NOTIFICATION =
  '<task-notification><summary>Agent "search" finished</summary><result>Found it at server.js:42</result></task-notification>';

test.describe('typedTextOf — what the user actually typed', () => {
  test('a plain prompt is itself', () => {
    expect(typedTextOf('fix the login bug')).toBe('fix the login bug');
  });

  // The #149 root cause. A genuine prompt arrives with injected context stapled
  // on, so equality against the raw turn text can never fire and the echo that
  // is waiting for this turn sits on screen forever.
  test('a TRAILING <system-reminder> is stripped', () => {
    expect(typedTextOf(`fix the login bug\n${REMINDER}`)).toBe('fix the login bug');
  });

  test('a LEADING <system-reminder> is stripped', () => {
    expect(typedTextOf(`${REMINDER}\nfix the login bug`)).toBe('fix the login bug');
  });

  test('a turn that is NOTHING BUT reminders was typed by nobody', () => {
    expect(typedTextOf(REMINDER)).toBe('');
  });

  // The trio, both orders. `body` is NOT usable here: it folds the
  // <command-message> prose in and yields '/clear clear'.
  test('a name-first command trio yields the bare slash command', () => {
    expect(typedTextOf(TRIO_NAME_FIRST)).toBe('/clear');
    // And why `body` cannot stand in for it: the <command-message> prose is
    // folded in alongside the name, so the value to compare against would be
    // '/clear clear' — never what anybody typed.
    expect(classifyUserTurn(TRIO_NAME_FIRST).body).toContain('/clear clear');
  });

  test('a message-first command trio yields the command AND its arguments', () => {
    // The shape a queued `/issue <text>` really has. Anchored parsing misses it:
    // classifyUserTurn's command branch uses startsWith, so this turn is not even
    // classified as a command — matching on the PRESENCE of <command-name> is
    // what makes the echo work.
    expect(typedTextOf(TRIO_MESSAGE_FIRST)).toBe(
      '/issue the queued badge never clears once the prompt is consumed',
    );
  });

  test('an empty <command-args> adds no trailing space', () => {
    expect(typedTextOf('<command-name>/compact</command-name>\n<command-args></command-args>')).toBe('/compact');
  });

  test('the caveat prose alone was typed by nobody', () => {
    // The command produced stdout, so the caveat arrives without its tag and
    // there is no <command-name> to recover.
    expect(typedTextOf(CAVEAT_ONLY)).toBe('');
  });

  test('nothing the harness injected is ever reported as typed', () => {
    expect(typedTextOf(TEAMMATE)).toBe('');
    expect(typedTextOf(TASK_NOTIFICATION)).toBe('');
    expect(typedTextOf('Stop hook feedback: keep going')).toBe('');
    expect(typedTextOf('This session is being continued from a previous conversation.')).toBe('');
  });

  test('non-string / empty input -> empty string (never throws)', () => {
    expect(typedTextOf('')).toBe('');
    expect(typedTextOf(null)).toBe('');
    expect(typedTextOf(undefined)).toBe('');
    expect(typedTextOf(42)).toBe('');
  });
});

// The rule moved OUT of lib/recap.js so lib/transcript.js could use it without
// closing the require cycle recap -> speech -> transcript. Every existing
// importer reads it from recap, so the re-export is load-bearing.
test.describe('the extraction kept lib/recap.js a valid owner for its importers', () => {
  test('recap re-exports the same classifyUserTurn and USER_KINDS', () => {
    expect(recap.classifyUserTurn).toBe(classifyUserTurn);
    expect(recap.USER_KINDS).toBe(USER_KINDS);
    expect(recap.classifyUserTurn(TRIO_NAME_FIRST).kind).toBe(USER_KINDS.COMMAND);
  });

  test('lib/transcript.js can require the rule without a cycle', () => {
    // The reason this module exists at all. If transcript.js ever reaches for
    // recap.js instead, one of these two exports comes back undefined.
    const transcript = require('../lib/transcript');
    expect(typeof transcript.parseTranscriptTurn).toBe('function');
    expect(typeof require('../lib/speech').extractSummary).toBe('function');
  });
});
