// @ts-check
// lib/user-turn.js — what a `role:user` turn actually IS, and what the human
// typed to produce it.
//
// The fixtures below are REAL wrapper shapes lifted from live transcripts, with
// the prose replaced. That matters more here than anywhere else in the suite,
// because #149 was caused by building on an INVENTED shape: a slash command was
// assumed to arrive as a lone `<command-name>/compact</command-name>`, and it
// never does — it is a tag TRIO, in either order, and the order that carries the
// user's arguments is the one that leads with `<command-message>`.
//
// `typedTextOf` is what the chat lens's optimistic "Queued" echo compares itself
// against. Its contract is narrow and absolute: the exact characters the user
// typed into the compose bar, or '' for every turn they typed nothing at all.
const { test, expect } = require('@playwright/test');
const { classifyUserTurn, typedTextOf, USER_KINDS } = require('../lib/user-turn');
const recap = require('../lib/recap');

// --- real wrapper shapes -----------------------------------------------------
// Name-first: what the harness itself writes for a bare `/compact`, `/clear`.
// The trio OPENS the turn — measured across 516 transcripts, every one of the 88
// genuine trios leads with `<command-name>` (59) or `<command-message>` (29).
// This fixture used to lead with a `<local-command-caveat>` block, which is an
// INVENTED shape: 62 turns lead with that tag and NOT ONE of them carries a trio.
const TRIO_NAME_FIRST = [
  '<command-name>/clear</command-name>',
  '<command-message>clear</command-message>',
  '<command-args></command-args>',
].join('\n');
// The caveat-leading class, kept so the deliberate exclusion above stays covered.
const CAVEAT_LEAD =
  '<local-command-caveat>Caveat: The messages below were generated by the user while running local commands. DO NOT respond to these messages.</local-command-caveat>';
// Message-first: the shape a user-typed `/name <text>` actually lands in. This
// is the one that matters for #149 — it is the shape that gets QUEUED.
const TRIO_MESSAGE_FIRST = [
  '<command-message>issue</command-message>',
  '<command-name>/issue</command-name>',
  '<command-args>the queued badge never clears once the prompt is consumed</command-args>',
].join('\n');
const CAVEAT_ONLY =
  'Caveat: The messages below were generated by the user while running local commands. DO NOT respond to these messages.';
const REMINDER = '<system-reminder>\n# claudeMd\nlots of injected instructions\n</system-reminder>';
const TEAMMATE =
  'Another Claude session sent a message: <teammate-message teammate_id="J4b2">please rebase</teammate-message>';
const TASK_NOTIFICATION =
  '<task-notification><summary>Agent "search" finished</summary><result>Found it at server.js:42</result></task-notification>';

test.describe('typedTextOf — what the user actually typed', () => {
  test('a plain prompt is itself', () => {
    expect(typedTextOf('fix the login bug')).toBe('fix the login bug');
  });

  // The #149 root cause. A genuine prompt arrives with injected context stapled
  // on, so equality against the raw turn text can never fire and the echo that
  // is waiting for this turn sits on screen forever.
  test('a TRAILING <system-reminder> is stripped', () => {
    expect(typedTextOf(`fix the login bug\n${REMINDER}`)).toBe('fix the login bug');
  });

  test('a LEADING <system-reminder> is stripped', () => {
    expect(typedTextOf(`${REMINDER}\nfix the login bug`)).toBe('fix the login bug');
  });

  test('a turn that is NOTHING BUT reminders was typed by nobody', () => {
    expect(typedTextOf(REMINDER)).toBe('');
  });

  // The trio, both orders. `body` is NOT usable here: it folds the
  // <command-message> prose in and yields '/clear clear'.
  test('a name-first command trio yields the bare slash command', () => {
    expect(typedTextOf(TRIO_NAME_FIRST)).toBe('/clear');
    // And why `body` cannot stand in for it: the <command-message> prose is
    // folded in alongside the name, so the value to compare against would be
    // '/clear clear' — never what anybody typed.
    expect(classifyUserTurn(TRIO_NAME_FIRST).body).toContain('/clear clear');
  });

  test('a message-first command trio yields the command AND its arguments', () => {
    // The shape a queued `/issue <text>` really has. classifyUserTurn's command
    // branch anchors on <command-name> alone, so this turn is not even classified
    // as a command — accepting BOTH opening tags here is what makes the echo work.
    expect(typedTextOf(TRIO_MESSAGE_FIRST)).toBe(
      '/issue the queued badge never clears once the prompt is consumed',
    );
  });

  test('an empty <command-args> adds no trailing space', () => {
    expect(typedTextOf('<command-name>/compact</command-name>\n<command-args></command-args>')).toBe('/compact');
  });

  test('the caveat prose alone was typed by nobody', () => {
    // The command produced stdout, so the caveat arrives without its tag and
    // there is no <command-name> to recover.
    expect(typedTextOf(CAVEAT_ONLY)).toBe('');
    // Tagged and leading, the same turn is still nobody's typed text. This is the
    // 62-turn class the anchor deliberately excludes.
    expect(typedTextOf(CAVEAT_LEAD)).toBe('');
  });

  // --- a QUOTED trio is not a RUN one ----------------------------------------
  // The extraction matched a bare `<command-name>` ANYWHERE in the turn, so every
  // turn that merely quoted one was reported as a typed slash command. Measured:
  // 9 of the 97 trio-carrying turns on this machine are quotes like these, and
  // every one of them was misread. Two consequences — the real sentence is lost,
  // and the echo is handed a key that can never match, which is #149 recurring.
  test('a sentence that merely CONTAINS a trio is not reported as a slash command', () => {
    const quoted = `what does this line mean?\n${TRIO_MESSAGE_FIRST}`;
    expect(typedTextOf(quoted)).not.toBe(
      '/issue the queued badge never clears once the prompt is consumed',
    );
    // The sentence the human actually typed survives.
    expect(typedTextOf(quoted)).toContain('what does this line mean?');
  });

  test('a teammate message QUOTING a trio was typed by nobody', () => {
    const bare = `<teammate-message teammate_id="J4b2">please look at ${TRIO_MESSAGE_FIRST}</teammate-message>`;
    expect(typedTextOf(bare)).toBe('');
    // The prose-prefixed form, which is how 3 of the 9 real ones arrive.
    expect(typedTextOf(`Another Claude session sent a message: ${bare}`)).toBe('');
  });

  test('a task-notification QUOTING a trio was typed by nobody', () => {
    expect(
      typedTextOf(
        `<task-notification><summary>Agent "search" finished</summary><result>${TRIO_MESSAGE_FIRST}</result></task-notification>`,
      ),
    ).toBe('');
  });

  test('a post-compaction summary QUOTING a trio was typed by nobody', () => {
    // The other 2 of the 9. A just-compacted session is precisely when the echo
    // and the recap are most likely to be read.
    expect(
      typedTextOf(`This session is being continued from a previous conversation.\n${TRIO_NAME_FIRST}`),
    ).toBe('');
  });

  test('nothing the harness injected is ever reported as typed', () => {
    expect(typedTextOf(TEAMMATE)).toBe('');
    expect(typedTextOf(TASK_NOTIFICATION)).toBe('');
    expect(typedTextOf('Stop hook feedback: keep going')).toBe('');
    expect(typedTextOf('This session is being continued from a previous conversation.')).toBe('');
  });

  test('non-string / empty input -> empty string (never throws)', () => {
    expect(typedTextOf('')).toBe('');
    expect(typedTextOf(null)).toBe('');
    expect(typedTextOf(undefined)).toBe('');
    expect(typedTextOf(42)).toBe('');
  });
});

// The rule moved OUT of lib/recap.js so lib/transcript.js could use it without
// closing the require cycle recap -> speech -> transcript. Every existing
// importer reads it from recap, so the re-export is load-bearing.
test.describe('the extraction kept lib/recap.js a valid owner for its importers', () => {
  test('recap re-exports the same classifyUserTurn and USER_KINDS', () => {
    expect(recap.classifyUserTurn).toBe(classifyUserTurn);
    expect(recap.USER_KINDS).toBe(USER_KINDS);
    expect(recap.classifyUserTurn(TRIO_NAME_FIRST).kind).toBe(USER_KINDS.COMMAND);
  });

  test('lib/transcript.js can require the rule without a cycle', () => {
    // The reason this module exists at all. If transcript.js ever reaches for
    // recap.js instead, one of these two exports comes back undefined.
    const transcript = require('../lib/transcript');
    expect(typeof transcript.parseTranscriptTurn).toBe('function');
    expect(typeof require('../lib/speech').extractSummary).toBe('function');
  });
});
