// @ts-check
// lib/user-turn.js — what a `role:user` turn actually IS, and what the human
// typed to produce it.
//
// The fixtures below are REAL wrapper shapes lifted from live transcripts, with
// the prose replaced. That matters more here than anywhere else in the suite,
// because #149 was caused by building on an INVENTED shape: a slash command was
// assumed to arrive as a lone `<command-name>/compact</command-name>`, and it
// never does — it is a tag TRIO, in either order, and the order that carries the
// user's arguments is the one that leads with `<command-message>`.
//
// `typedTextOf` is what the chat lens's optimistic "Queued" echo compares itself
// against. Its contract is narrow and absolute: the exact characters the user
// typed into the compose bar, or '' for every turn they typed nothing at all.
const { test, expect } = require('@playwright/test');
const { classifyUserTurn, typedTextOf, USER_KINDS } = require('../lib/user-turn');
const recap = require('../lib/recap');

// --- real wrapper shapes -----------------------------------------------------
// Name-first: what the harness itself writes for a bare `/compact`, `/clear`.
// The trio OPENS the turn — measured across 516 transcripts, every one of the 88
// genuine trios leads with `<command-name>` (59) or `<command-message>` (29).
// This fixture used to lead with a `<local-command-caveat>` block, which is an
// INVENTED shape: 62 turns lead with that tag and NOT ONE of them carries a trio.
const TRIO_NAME_FIRST = [
  '<command-name>/clear</command-name>',
  '<command-message>clear</command-message>',
  '<command-args></command-args>',
].join('\n');
// The caveat-leading class, kept so the deliberate exclusion above stays covered.
const CAVEAT_LEAD =
  '<local-command-caveat>Caveat: The messages below were generated by the user while running local commands. DO NOT respond to these messages.</local-command-caveat>';
// Message-first: the shape a user-typed `/name <text>` actually lands in. This
// is the one that matters for #149 — it is the shape that gets QUEUED.
const TRIO_MESSAGE_FIRST = [
  '<command-message>issue</command-message>',
  '<command-name>/issue</command-name>',
  '<command-args>the queued badge never clears once the prompt is consumed</command-args>',
].join('\n');
const CAVEAT_ONLY =
  'Caveat: The messages below were generated by the user while running local commands. DO NOT respond to these messages.';
const REMINDER = '<system-reminder>\n# claudeMd\nlots of injected instructions\n</system-reminder>';
const TEAMMATE =
  'Another Claude session sent a message: <teammate-message teammate_id="J4b2">please rebase</teammate-message>';
const TASK_NOTIFICATION =
  '<task-notification><summary>Agent "search" finished</summary><result>Found it at server.js:42</result></task-notification>';

test.describe('typedTextOf — what the user actually typed', () => {
  test('a plain prompt is itself', () => {
    expect(typedTextOf('fix the login bug')).toBe('fix the login bug');
  });

  // The #149 root cause. A genuine prompt arrives with injected context stapled
  // on, so equality against the raw turn text can never fire and the echo that
  // is waiting for this turn sits on screen forever.
  test('a TRAILING <system-reminder> is stripped', () => {
    expect(typedTextOf(`fix the login bug\n${REMINDER}`)).toBe('fix the login bug');
  });

  test('a LEADING <system-reminder> is stripped', () => {
    expect(typedTextOf(`${REMINDER}\nfix the login bug`)).toBe('fix the login bug');
  });

  test('a turn that is NOTHING BUT reminders was typed by nobody', () => {
    expect(typedTextOf(REMINDER)).toBe('');
  });

  // The trio, both orders. `body` is NOT usable here: it folds the
  // <command-message> prose in and yields '/clear clear'.
  test('a name-first command trio yields the bare slash command', () => {
    expect(typedTextOf(TRIO_NAME_FIRST)).toBe('/clear');
    // And why `body` cannot stand in for it: the <command-message> prose is
    // folded in alongside the name, so the value to compare against would be
    // '/clear clear' — never what anybody typed.
    expect(classifyUserTurn(TRIO_NAME_FIRST).body).toContain('/clear clear');
  });

  test('a message-first command trio yields the command AND its arguments', () => {
    // The shape a queued `/issue <text>` really has. classifyUserTurn's command
    // branch anchors on <command-name> alone, so this turn is not even classified
    // as a command — accepting BOTH opening tags here is what makes the echo work.
    expect(typedTextOf(TRIO_MESSAGE_FIRST)).toBe(
      '/issue the queued badge never clears once the prompt is consumed',
    );
  });

  test('an empty <command-args> adds no trailing space', () => {
    expect(typedTextOf('<command-name>/compact</command-name>\n<command-args></command-args>')).toBe('/compact');
  });

  test('the caveat prose alone was typed by nobody', () => {
    // The command produced stdout, so the caveat arrives without its tag and
    // there is no <command-name> to recover.
    expect(typedTextOf(CAVEAT_ONLY)).toBe('');
    // Tagged and leading, the same turn is still nobody's typed text. This is the
    // 62-turn class the anchor deliberately excludes.
    expect(typedTextOf(CAVEAT_LEAD)).toBe('');
  });

  // --- a QUOTED trio is not a RUN one ----------------------------------------
  // The extraction matched a bare `<command-name>` ANYWHERE in the turn, so every
  // turn that merely quoted one was reported as a typed slash command. Measured:
  // 9 of the 97 trio-carrying turns on this machine are quotes like these, and
  // every one of them was misread. Two consequences — the real sentence is lost,
  // and the echo is handed a key that can never match, which is #149 recurring.
  test('a sentence that merely CONTAINS a trio is not reported as a slash command', () => {
    const quoted = `what does this line mean?\n${TRIO_MESSAGE_FIRST}`;
    expect(typedTextOf(quoted)).not.toBe(
      '/issue the queued badge never clears once the prompt is consumed',
    );
    // The sentence the human actually typed survives.
    expect(typedTextOf(quoted)).toContain('what does this line mean?');
  });

  test('a teammate message QUOTING a trio was typed by nobody', () => {
    const bare = `<teammate-message teammate_id="J4b2">please look at ${TRIO_MESSAGE_FIRST}</teammate-message>`;
    expect(typedTextOf(bare)).toBe('');
    // The prose-prefixed form, which is how 3 of the 9 real ones arrive.
    expect(typedTextOf(`Another Claude session sent a message: ${bare}`)).toBe('');
  });

  test('a task-notification QUOTING a trio was typed by nobody', () => {
    expect(
      typedTextOf(
        `<task-notification><summary>Agent "search" finished</summary><result>${TRIO_MESSAGE_FIRST}</result></task-notification>`,
      ),
    ).toBe('');
  });

  test('a post-compaction summary QUOTING a trio was typed by nobody', () => {
    // The other 2 of the 9. A just-compacted session is precisely when the echo
    // and the recap are most likely to be read.
    expect(
      typedTextOf(`This session is being continued from a previous conversation.\n${TRIO_NAME_FIRST}`),
    ).toBe('');
  });

  test('nothing the harness injected is ever reported as typed', () => {
    expect(typedTextOf(TEAMMATE)).toBe('');
    expect(typedTextOf(TASK_NOTIFICATION)).toBe('');
    expect(typedTextOf('Stop hook feedback: keep going')).toBe('');
    expect(typedTextOf('This session is being continued from a previous conversation.')).toBe('');
  });

  test('non-string / empty input -> empty string (never throws)', () => {
    expect(typedTextOf('')).toBe('');
    expect(typedTextOf(null)).toBe('');
    expect(typedTextOf(undefined)).toBe('');
    expect(typedTextOf(42)).toBe('');
  });
});

// The rule moved OUT of lib/recap.js so lib/transcript.js could use it without
// closing the require cycle recap -> speech -> transcript. Every existing
// importer reads it from recap, so the re-export is load-bearing.
test.describe('the extraction kept lib/recap.js a valid owner for its importers', () => {
  test('recap re-exports the same classifyUserTurn and USER_KINDS', () => {
    expect(recap.classifyUserTurn).toBe(classifyUserTurn);
    expect(recap.USER_KINDS).toBe(USER_KINDS);
    expect(recap.classifyUserTurn(TRIO_NAME_FIRST).kind).toBe(USER_KINDS.COMMAND);
  });

  test('lib/transcript.js can require the rule without a cycle', () => {
    // The reason this module exists at all. If transcript.js ever reaches for
    // recap.js instead, one of these two exports comes back undefined.
    const transcript = require('../lib/transcript');
    expect(typeof transcript.parseTranscriptTurn).toBe('function');
    expect(typeof require('../lib/speech').extractSummary).toBe('function');
  });
});

// --- #163: a skill body is injected with NO wrapper to sniff ------------------
// The one injection with no content signature. Claude Code expands a skill into
// a `role:user` turn carrying the whole SKILL.md, and — unlike a slash command —
// wraps it in NOTHING. Every signature above misses it, so it classified as
// `human`: the chat lens labelled 142 KB of skill instructions "You" and the
// recap reported it as the user's last prompt.
//
// The transcript record answers it structurally: the harness sets `isMeta: true`.
// Re-measured 2026-08-26 over 803 transcripts / 3153 `role:user` turns —
// 648 `isMeta:true` (51 bare skill bodies, 222 reminder-only, 375 other
// injections) and 2505 `isMeta:false`, of which 2363 are genuine prompts and
// **not one** genuine prompt carries the flag. Two facts drive the design:
//   * ALL 142 `<command-name>` trios in that corpus are `isMeta:FALSE`, so the
//     flag COMPLEMENTS the command signature and must never replace it.
//   * Two of the skill bodies do not open with `Base directory for this skill:`
//     at all, which is exactly why this is a structural flag and not a fourth
//     content signature.
const SKILL_BODY_BASEDIR = [
  'Base directory for this skill: /skills/example-skill',
  '',
  '# Example skill',
  '',
  'Do the thing, then report what you saw.',
].join('\n');
// The two measured openings that a `Base directory` sniff would MISS. If the fix
// ever regresses into a content check, these two go red first.
const SKILL_BODY_HEADING = [
  '# Frontend Design',
  '',
  'Approach this as the design lead at a small studio.',
].join('\n');
const SKILL_BODY_PROSE =
  'Review the current diff for correctness bugs and reuse cleanups at the given effort level.';
const SKILL_BODIES = [SKILL_BODY_BASEDIR, SKILL_BODY_HEADING, SKILL_BODY_PROSE];

test.describe('#163 — an injected skill body is not a prompt', () => {
  test('WITHOUT the flag every one of them still reads as human (the bug)', () => {
    // Pinned deliberately: it is the proof that no content signature can catch
    // these, and therefore that the structural flag is doing the work.
    for (const body of SKILL_BODIES) {
      expect(classifyUserTurn(body).kind).toBe(USER_KINDS.HUMAN);
    }
  });

  test('isMeta:true makes a signature-less turn `meta`, never human', () => {
    for (const body of SKILL_BODIES) {
      const c = classifyUserTurn(body, { isMeta: true });
      expect(c.kind).toBe(USER_KINDS.META);
      expect(c.kind).not.toBe(USER_KINDS.HUMAN);
      // The text survives — a skill body is not nothing, it is just not YOURS.
      expect(c.body).toBe(body);
    }
  });

  test('typedTextOf returns "" for one, so #149\'s Queued echo cannot match it', () => {
    for (const body of SKILL_BODIES) {
      expect(typedTextOf(body, { isMeta: true })).toBe('');
    }
  });

  // The correction to the issue's own numbers: command trios are isMeta:FALSE in
  // the corpus, so the flag ADDS to the signatures rather than replacing them.
  test('a genuine prompt is untouched — isMeta absent or false stays human', () => {
    expect(classifyUserTurn('fix the login bug').kind).toBe(USER_KINDS.HUMAN);
    expect(classifyUserTurn('fix the login bug', {}).kind).toBe(USER_KINDS.HUMAN);
    expect(classifyUserTurn('fix the login bug', { isMeta: false }).kind).toBe(USER_KINDS.HUMAN);
    expect(typedTextOf('fix the login bug', { isMeta: false })).toBe('fix the login bug');
    // And a prompt carrying injected context is still the sentence, not 'meta'.
    expect(typedTextOf(`fix the login bug\n${REMINDER}`, { isMeta: false })).toBe('fix the login bug');
  });

  test('a content signature still WINS over the flag — the label is better', () => {
    // A signature names its source ('Hook', the teammate id, the command); 'meta'
    // can only say "the harness put this here". Never trade a name for a shrug.
    expect(classifyUserTurn(TEAMMATE, { isMeta: true }).kind).toBe(USER_KINDS.TEAMMATE);
    expect(classifyUserTurn(TASK_NOTIFICATION, { isMeta: true }).kind).toBe(USER_KINDS.SYSTEM);
    expect(classifyUserTurn(TRIO_NAME_FIRST, { isMeta: true }).kind).toBe(USER_KINDS.COMMAND);
    // A slash command the user typed is STILL typed, flag or no flag.
    expect(typedTextOf(TRIO_MESSAGE_FIRST, { isMeta: true })).toBe(
      '/issue the queued badge never clears once the prompt is consumed',
    );
  });

  test('an oversized body costs nothing to classify', () => {
    const huge = `${SKILL_BODY_BASEDIR}\n${'x'.repeat(142619)}`;
    expect(classifyUserTurn(huge, { isMeta: true }).kind).toBe(USER_KINDS.META);
    expect(typedTextOf(huge, { isMeta: true })).toBe('');
  });
});

// --- the flag has to REACH the rule, and the clients have to see the verdict --
test.describe('#163 — lib/transcript.js reads isMeta and publishes the verdict', () => {
  const { parseTranscriptTurn } = require('../lib/transcript');
  const line = (text, extra = {}) =>
    JSON.stringify({ type: 'user', message: { role: 'user', content: text }, ...extra });

  test('a bare skill body on an isMeta record is published as `meta`', () => {
    const t = parseTranscriptTurn(line(SKILL_BODY_HEADING, { isMeta: true }));
    expect(t.role).toBe('user');
    expect(t.userKind).toBe(USER_KINDS.META);
    expect(t.typedText).toBe('');
  });

  test('the same text WITHOUT the flag is still a human prompt', () => {
    const t = parseTranscriptTurn(line(SKILL_BODY_HEADING));
    expect(t.userKind).toBe(USER_KINDS.HUMAN);
    expect(t.typedText).toBe(SKILL_BODY_HEADING);
  });

  test('an ordinary prompt is published as human — the guard', () => {
    const t = parseTranscriptTurn(line('fix the login bug'));
    expect(t.userKind).toBe(USER_KINDS.HUMAN);
    expect(t.typedText).toBe('fix the login bug');
  });

  test('a command trio still publishes `command`, not `meta`', () => {
    const t = parseTranscriptTurn(line(TRIO_NAME_FIRST));
    expect(t.userKind).toBe(USER_KINDS.COMMAND);
  });
});

// --- #192: a command's OUTPUT is not the user's prompt ------------------------
// Reported 2026-08-31 with a screenshot: a "You" bubble containing `/compact`'s
// own stdout plus our hook's JSON, presented as the user's words.
//
// Measured 2026-08-31 over 1066 transcripts / 3902 `role:user` turns:
//   * 61 turns LEAD with `<local-command-stdout>`, and all 61 classified `human`;
//   * not one carries `isMeta` (so #163's structural backstop cannot catch it)
//     and not one carries a `<command-name>` (so the trio anchor cannot either);
//   * 47 of the 61 carry SGR escapes, because the text was captured off a terminal;
//   * exactly ONE turn in the whole corpus contains the tag WITHOUT leading — and
//     it is a genuine prompt, asking how this very label is decided. An
//     unanchored `includes` would have swallowed it. That is #138's lesson
//     (this repo's own text is a live input) reproduced in the corpus, and it is
//     why the anchor is `startsWith`.
//
// SYSTEM, NOT COMMAND — and that is forced by the CONSUMER, not by taste.
// `conversation_view.dart:1428` maps the wire's `command` onto
// `UserTurnKind.human` deliberately (a slash command IS your own turn, and #32's
// collapsed chip renders on the human branch). So publishing `command` here
// would leave the reported "You" bubble exactly as it is. A NEW kind is worse
// still: `userTurnKindFromWire` returns null for an unrecognised string, the
// client falls back to its weaker Dart classifier, and the turn reads as human
// again — so an invented kind would ship the bug to every client that has not
// been rebuilt. `system` is the one verdict that renders muted, left-aligned and
// unlabelled-as-you on the CURRENT companion, with no client release at all.
const STDOUT_LEAD = [
  '<local-command-stdout>\x1b[2mCompacted (ctrl+o to see full summary)\x1b[22m',
  '\x1b[2mPreCompact [http://127.0.0.1:7681/api/hook] completed successfully: '
    + '{"ok":true,"status":"idle"}\x1b[22m</local-command-stdout>',
].join('\n');
// The corpus's single non-leading occurrence, in shape: a real prompt that names
// the tag while asking about it. This one must stay `human`.
const STDOUT_QUOTED = [
  'In ai-terminal/lib, work out what decides the author label on a chat bubble',
  'for a <local-command-stdout> turn. Answer with file:line.',
].join('\n');

test.describe('#192 — command output is never the user\'s prompt', () => {
  test('a <local-command-stdout>-leading turn is NOT human', () => {
    // Red before the fix: all 61 corpus turns of this shape reached the final
    // `return { kind: HUMAN }`.
    expect(classifyUserTurn(STDOUT_LEAD).kind).not.toBe(USER_KINDS.HUMAN);
  });

  test('it is SYSTEM specifically — `command` would still render as "You"', () => {
    // Pinned on the exact value, not merely "not human": `command` maps to
    // UserTurnKind.human on the companion, so it would not fix the report.
    const c = classifyUserTurn(STDOUT_LEAD);
    expect(c.kind).toBe(USER_KINDS.SYSTEM);
    expect(c.from).toBe('Command output');
  });

  test('the body is readable — tags and terminal escapes both gone', () => {
    const { body } = classifyUserTurn(STDOUT_LEAD);
    expect(body).not.toContain('\x1b');
    expect(body).not.toContain('local-command-stdout');
    expect(body).toContain('Compacted (ctrl+o to see full summary)');
  });

  test('typedTextOf is empty, so #149\'s Queued echo can never match it', () => {
    expect(typedTextOf(STDOUT_LEAD)).toBe('');
  });

  test('a genuine prompt that merely NAMES the tag stays human', () => {
    // The corpus's one non-leading occurrence. An `includes` sniff loses it.
    const c = classifyUserTurn(STDOUT_QUOTED);
    expect(c.kind).toBe(USER_KINDS.HUMAN);
    expect(typedTextOf(STDOUT_QUOTED)).toContain('author label');
  });

  test('the trio a human TYPED is untouched — still `command`, still their turn', () => {
    // The guard on the blast radius: this fix must not reclassify the command
    // the user actually typed, which is a different turn from its output.
    expect(classifyUserTurn(TRIO_NAME_FIRST).kind).toBe(USER_KINDS.COMMAND);
    expect(classifyUserTurn(CAVEAT_LEAD).kind).toBe(USER_KINDS.COMMAND);
  });

  test('the recap stops reporting it as the last prompt', () => {
    // The second consumer #192 names, fixed by the same one-owner change.
    expect(recap.isHumanPrompt({ role: 'user', text: STDOUT_LEAD })).toBe(false);
  });

  test('published end-to-end on the wire as `system`', () => {
    const { parseTranscriptTurn } = require('../lib/transcript');
    const t = parseTranscriptTurn(JSON.stringify({
      type: 'user', message: { role: 'user', content: STDOUT_LEAD },
    }));
    expect(t.userKind).toBe(USER_KINDS.SYSTEM);
    expect(t.typedText).toBe('');
  });
});
